services:
  # MariaDB
  mariadb:
    build: ./requirements/mariadb
    image: mehernan/mariadb
    container_name: mariadb
    volumes:
#      - mariadb_data:/home/mysqluser/data
#      - /home/mehernan/data/mariadb:/var/lib/mysql
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  # WordPress
  wordpress:
    build: ./requirements/wordpress
    image: mehernan/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      #    - wordpress_data:/var/www/html
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  # NGINX
  nginx:
    build: ./requirements/nginx
    image: mehernan/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/mehernan/data/mariadb"
      o: bind
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/mehernan/data/wordpress"
      o: bind
      type: none 

networks:
  inception:
    driver: bridge

