services:
  # MariaDB
  mariadb:
    build: ./requirements/mariadb
    # image: mariadb:12.0.2
    container_name: mariadb
    ports: #changed
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  # WordPress
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  # NGINX
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mehernan/data/mariadb"

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mehernan/data/wordpress"

networks:
  inception:
    driver: bridge

