services:
  # MariaDB
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadb_data:/home/mysqluser/data
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  # WordPress
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  # NGINX
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/mehernan/data/mariadb"
      o: bind
      type: none
  wordpress_data:

    driver: local
    driver_opts:
      device: "/home/mehernan/data/wordpress"
      o: bind
      type: none 

networks:
  inception:
    driver: bridge

